### PR TITLE
PLAT-3212 new enpoint to fetch all user with additional information

### PR DESCRIPTION
**Pull request by symphonydarlys**

### CODE REVIEW

**Comment by pmonks** [comment]
@symphonydarlys you should now be in the cla-bot's whitelist.  If you "touch" this PR (e.g. by adding an empty commit to it) the cla-bot will be retriggered.

**Comment by symphonydarlys** [comment]
now it is possible to merge this PR please @pmonks .

**Comment by dnsymphony** [comment]
No.  I'll take care of the update.

**Comment by pmonks** [comment]
@dnsymphony don't worry - I don't have permission to merge into anyone's repos anyway.  😉

**Pull request closed without merging**
