### PR TITLE
PLAT-10669 Update Room V3 API to Pin/Unpin a message

### PR DESCRIPTION
**Pull request by symphony-mariacristina**
Adding pinnedMessageId field to the Update Room V3 api and Get Info v3 in order to unable a bot to pin/unpin a message inside a room

### CODE REVIEW

**Review by symphony-youri — APPROVED** [review]

**Review by symphony-thibault — CHANGES_REQUESTED** [review]
@symphony-mariacristina Is this new field really part of current specs version (`20.10.0`)?  I believe that it will only be part of SBE `20.13.0` right?

**Comment by symphony-mariacristina** [comment]
> @symphony-mariacristina Is this new field really part of current specs version (`20.10.0`)? I believe that it will only be part of SBE `20.13.0` right?

You are right @symphony-thibault! Thanks for noticing that. Don't know why I though the master branch here was `20.13` as well.

**Comment by symphony-youri** [comment]
Did not we already branch for 20.10 and master is the next version to come?

**Comment by symphony-mariacristina** [comment]
> Did not we already branch for 20.10 and master is the next version to come?

@symphony-youri We are missing the `20.12` before.

**Comment by symphony-thibault** [comment]
> Did not we already branch for 20.10 and master is the next version to come?

That's not how we work today, `master` is the latest version.  This might change though if we decide to generate BE code from this repo.

**Pull request closed without merging**
