### PR TITLE
PLAT-10675: Add Postman collection, cleanups

### PR DESCRIPTION
**Pull request by symphony-youri**
Added Postman collection and test environment along with the specs.
It will be easier to maintain this file.

Also updated a few files to follow the Finos blueprints, cleanup Maven
dependencies.

--- 

The Postman collection is difficult to review, I suggest to import it in Postman if you want to check it. (I mostly took it from the developer website)

### CODE REVIEW

**Comment by symphony-mariacristina** [comment]
Should we maybe remove firehose endpoints from the postman collection?

**Review by symphony-thibault — APPROVED** [review]

**Comment by symphony-thibault** [comment]
> Should we maybe remove firehose endpoints from the postman collection?

We could plan a collection cleanup for later. Depending on Youri's motivation to do it as part of this PR :)

**Review by symphony-mariacristina — APPROVED** [review]
LGTM! 
I guess creating a follow up ticket to review this collection it can be good. I see there are also some endpoints missing (like v5/datafeeds or follow/unfollow).

**Comment by symphony-youri** [comment]
Done!
I extracted the user id from the JWT when we login so we use it as a variable for the follow endpoints
For datafeed I also store the DF id and the ack id so we can make new calls to read events with the updated ack id

**Pull request merged**
