### PR TITLE
aligning README.md and CONTRIBUTING.md to FINOS project blueprint language

### PR DESCRIPTION
**Pull request by nikoganev**
aligning README.md and CONTRIBUTING.md to FINOS project blueprint language

### CODE REVIEW

**Comment by cristiadu** [comment]
@nikoganev is this still appliable? Also, this repository is to share the symphony swagger spec, so it must be updated by someone from the organization.

**Comment by nikoganev** [comment]
@cristiadu this was created almost 6 months ago. I was working for FINOS at that point of time and symphonyoss was a program hosted inside FINOS. Please reach out to 
@maoo or @brooklynrob  if you have any questions

**Comment by maoo** [comment]
@cristiadu - thanks for reaching out; yes, the PR is still applicable.

**Comment by cristiadu** [comment]
Thank you! @maoo @nikoganev . I will merge the PR.

**Pull request merged**
