### PR TITLE
Patching agent api so that deprecated is superset of current

### PR DESCRIPTION
**Pull request by robmoffat**

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@robmoffat). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If you still have any questions or just don't know what to do next, please email [help@finos.org](mailto:help@finos.org). /CC @finos-admin

**Comment by robmoffat** [comment]
It's not clear at all how to sign the CLA, even from reading the link.  Also, as a DB employee, we have a company-level CCLA with finos, so I shouldn't need to sign anything.

**Comment by maoo** [comment]
Hi @robmoffat ! Yes, you're covered by DB CCLA. I'll check the cla bot configuration and update you shortly on this PR

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by symphony-thibault** [comment]
@robmoffat Fixed by PR #71. This one can be closed. We will also take care of backports to branches `20.3.1`, `20.4.1` and `20.5.1`. Thanks!

**Comment by robmoffat** [comment]
> @robmoffat Fixed by PR #71. This one can be closed. We will also take care of backports to branches `20.3.1`, `20.4.1` and `20.5.1`. Thanks!

Awesome, cheers

**Pull request closed without merging**
